# toml-docs-start netlify
[build]
    publish = "public"
    command = "npm run build"

[build.environment]
    DART_SASS_VERSION = "1.66.1"
    HUGO_VERSION = "0.118.2"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"
    NODE_VERSION = "18.17.1"
    NPM_VERSION = "9.6.7"
# toml-docs-end netlify

[[headers]] 
    for = "/*"
    [headers.values]
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-XSS-Protection = "1; mode=block"
        Content-Security-Policy = """\
            default-src 'none'; \
            child-src 'self'; \
            script-src 'self' 'report-sample' https://utteranc.es/client.js https://gc.zgo.at/count.v3.js; \
            style-src 'self' 'unsafe-hashes' 'report-sample' https://utteranc.es https://www.youtube.com \
                'sha256-kFAIUwypIt04FgLyVU63Lcmp2AQimPh/TdYjy04Flxs=' 'sha256-XzJlZKVo+ff9ozww9Sr2p/2TbJXITZuaWMZ9p53zN1U=' \
                'sha256-hqhQ1AAR6jgr9lel8hs9sNOeqSwsGx6HH+B7TkLcmyY=' 'sha256-9HupEqQsOKAA3TMVtaZh8USULhFpwYGuWFk+44sVSgg=' \
                'sha256-uVrOu323DbALvO9XLsXSo1N3peMVuTC/lcentqDkW8A=' `sha256-1EpgJ5nIw5yOjtb0quQYVzvUweFMnvzELI9pm3pgbtc=';\
            object-src 'self'; \
            base-uri 'self'; \
            connect-src 'self' https://myrthos.goatcounter.com/count; \
            font-src 'self' ; \
            frame-src 'self' https://utteranc.es https://www.youtube-nocookie.com https://www.youtube.com; \
            frame-ancestors 'none'; \
            img-src 'self' data: https://i.vimeocdn.com https://i.ytimg.com https://img.youtube.com https://myrthos.goatcounter.com/count; \
            manifest-src 'self'; \
            media-src 'self'; \
            form-action 'self'; \
            """
        X-Frame-Options = "SAMEORIGIN"
        Referrer-Policy = "strict-origin"
        Permissions-Policy = """\
            geolocation=(), \
            midi=(), \
            sync-xhr=(), \
            microphone=(), \
            camera=(), \
            magnetometer=(), \
            gyroscope=(), \
            fullscreen=(), \
            payment=() \
            """
        cache-control = """\
            max-age=0, \
            no-cache, \
            no-store, \
            must-revalidate \
            """
        Access-Control-Allow-Origin = "*"

[context.deploy-preview]
    command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
    command = "npm run build -- -b $DEPLOY_PRIME_URL"

[dev]
    framework = "#custom"
    command = "npm run start"
    targetPort = 1313
    port = 8888
    publish = "public"
    autoLaunch = false

# toml-docs-start plugins
[[plugins]]
    package = "@gethinode/netlify-plugin-dartsass"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"
	[plugins.inputs]
	# Redirected in exampleSite/config/_default/hugo.toml
	# srcdir = ""

[[plugins]]
    package = "@netlify/plugin-lighthouse"
    # [plugins.inputs]
    # output_path = "reports/lighthouse.html"
# toml-docs-end plugins
