name: Lint & build
on:
  workflow_dispatch:
  push:
    tags:
      - v*
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CACHE_KEY: 'hugo-hinode'
  CACHE_PATH_POSIX: '/tmp/hugo_cache_runner'
  CACHE_PATH_WIN: '~\AppData\Local\hugo_cache'

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Perform clean install of npm
      run: npm ci

    - name: Lint the source files
      run: npm run lint      

  build:
    needs: lint

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [16.x, 18.x, 20.x]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Perform clean install of npm
      run: npm ci

    # Cache Hugo cachedir and resourcedir (configured in config/ci/hugo.toml) for each OS
    # No additional cache invalidation is needed, Hugo uses checksums itself
    - name: Use Hugo cache
      uses: actions/cache@v3
      with:
        path: ${{ runner.os == 'Windows' && env.CACHE_PATH_WIN || env.CACHE_PATH_POSIX }}
        key: ${{ runner.os }}-${{ env.CACHE_KEY }}
        restore-keys: |
          ${{ runner.os }}-${{ env.CACHE_KEY }}

    - name: Build main site
      run: npm run build:cache

    # The example site is to be published to demo.gethinode.com
    - name: Build example site
      run: npm run build:example:ci
